import { motion } from "framer-motion";
import { Code2, Database, Globe2 } from "lucide-react";

const focusAreas = [{ icon: Code2, title: "Full-stack applications", text: "Building connected frontend and backend experiences for practical web products." }, { icon: Globe2, title: "Responsive frontend development", text: "Creating clear, adaptable interfaces with React.js and modern CSS tools." }, { icon: Database, title: "APIs and data", text: "Working with REST APIs, Node.js, Express.js, and MongoDB." }];

function About({ darkMode }) {
  return <section id="about" className={`relative py-24 md:py-32 ${darkMode ? "section-dark-alt" : "section-light-alt"}`}><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><p className="text-sm font-semibold uppercase tracking-wider text-cyan-500">About</p><h2 className={`mt-3 font-heading text-3xl font-bold md:text-4xl ${darkMode ? "text-white" : "text-slate-900"}`}>A developer focused on useful, well-crafted web experiences.</h2><div className={`mt-6 space-y-4 leading-relaxed ${darkMode ? "text-slate-300" : "text-slate-600"}`}><p>I’m a MERN Stack Developer and BSCS Graduate focused on full-stack web applications, responsive frontend development, and practical client-oriented solutions.</p><p>I work with React.js to build polished interfaces and use Node.js, Express.js, MongoDB, and REST APIs to support dependable application functionality.</p></div></motion.div><div className="grid gap-4">{focusAreas.map(({ icon: Icon, title, text }, index) => <motion.article key={title} initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className={`flex gap-4 rounded-2xl border p-5 ${darkMode ? "border-white/10 bg-slate-900/60" : "border-slate-200 bg-white"}`}><div className="h-fit rounded-xl bg-cyan-500/10 p-3 text-cyan-500"><Icon size={21} /></div><div><h3 className={`font-heading font-semibold ${darkMode ? "text-white" : "text-slate-900"}`}>{title}</h3><p className={`mt-1 text-sm leading-relaxed ${darkMode ? "text-slate-300" : "text-slate-600"}`}>{text}</p></div></motion.article>)}</div></div></div></section>;
}
export default About;
